'use strict';
// Profile data model: parent/child groups, assignment, ordering, and JSON
// import/export/validation. Mutators call refresh() (main.js) instead of the
// inline renderGroups();stats();draw();exportJson() tail (review #4, #14).
// Exceptions: moveSelectedInChild and the reverse handler (view.js) keep the
// partial tail renderGroups();draw();exportJson() (no stats()) because reorder
// and reverse do not change assigned.size — calling refresh() would be a
// harmless no-op but would deviate from master-exact behavior, so it is kept inline.

function isRotoProfile(name=currentProfile){return name==='roto'}
function isGridProfile(name=currentProfile){return name==='grid'}
function resetSelection(){selected=null; hovered=null; filter={mode:'all',parentId:null,childId:null};}
function saveProfileState(){profiles[currentProfile].parents=parents; profiles[currentProfile].assigned=assigned; profiles[currentProfile].activeChild=activeChild}
function useProfile(name){saveProfileState(); currentProfile=PROFILE_NAMES.includes(name)?name:'full'; const state=profiles[currentProfile]; parents=state.parents; assigned=state.assigned; activeChild=state.activeChild; resetSelection(); updateProfileHint(); updateProfileUi(); ensureGridProfileRoot(); refresh();}
function resetCurrentProfile(){parents=[]; assigned=new Map(); activeChild=null; profiles[currentProfile]= {parents,assigned,activeChild}; selected=null; filter={mode:'all',parentId:null,childId:null}; ensureGridProfileRoot();}
function resetAllProfiles(){for(const name of PROFILE_NAMES)profiles[name]=emptyProfile(); currentProfile='full'; parents=profiles.full.parents; assigned=profiles.full.assigned; activeChild=null; selected=null; filter={mode:'all',parentId:null,childId:null}; const ps=el('profileSelect'); if(ps)ps.value=currentProfile; updateProfileHint(); updateProfileUi();}
function allChildren(){return parents.flatMap(p=>p.children.map(c=>({...c,parent:p})))}
function findChild(id){for(const p of parents){const c=p.children.find(x=>x.id===id); if(c)return {parent:p,child:c};} return null}
function childIdsOfParent(pid){const p=parents.find(x=>x.id===pid); return new Set((p?.children||[]).map(c=>c.id))}
function childIdsForPoint(id){return assigned.get(id)||new Set()}
function pointHasChild(id,cid){return childIdsForPoint(id).has(cid)}
function primaryChildIdForPoint(id){const ids=[...childIdsForPoint(id)]; return ids.includes(activeChild)?activeChild:(ids[0]||null)}
function removePointFromChild(id,cid){const found=findChild(cid); if(found){found.child.ids=found.child.ids.filter(x=>x!==id); if(isGridProfile()&&found.child.grid){for(const p of found.child.grid.points){if(p.id===id)p.id=null;}}} const ids=assigned.get(id); if(ids){ids.delete(cid); if(!ids.size)assigned.delete(id);}}
function addParent(name){name=(name||el('parentName').value).trim(); if(!name){appToast('Enter a parent group name.','error');return null} if(parents.some(p=>p.name===name)){appToast('That parent already exists.','error');return parents.find(p=>p.name===name)} const p={id:uid('p'),name,children:[],collapsed:false}; parents.push(p); el('parentName').value=''; renderGroups(); exportJson(); appToast('Parent created.','ok'); return p;}
function makeChild(name,color){const c={id:uid('c'),name,color:color||COLORS[allChildren().length%COLORS.length],ids:[],openSpline:false}; if(isGridProfile())createGrid(c,3,2); return c;}
function addChild(parentId,name,color){parentId=parentId||el('parentSelect').value; const p=parents.find(x=>x.id===parentId); if(!p){appToast('Create a parent first.','error');return null} name=(name||el('childName').value).trim(); if(!name){appToast('Enter a child group name.','error');return null} if(p.children.some(c=>c.name===name)){appToast('That child already exists in this parent.','error');return p.children.find(c=>c.name===name)} const c=makeChild(name,color||el('childColor').value||COLORS[allChildren().length%COLORS.length]); p.collapsed=false; p.children.push(c); activeChild=c.id; el('childName').value=''; el('childColor').value=COLORS[(allChildren().length+1)%COLORS.length]; refresh(); appToast('Child created.','ok'); return c;}
function getOrCreateParent(name){let p=parents.find(x=>x.name===name); if(!p){p={id:uid('p'),name,children:[],collapsed:false}; parents.push(p);} return p;}
function getOrCreateChild(parentName,childName,color){const p=getOrCreateParent(parentName); let c=p.children.find(x=>x.name===childName); if(!c){c=makeChild(childName,color||COLORS[allChildren().length%COLORS.length]); p.children.push(c);} else if(color){c.color=color;} return c;}
function moveSelectedInChild(c,delta){if(selected==null){appToast('Select a landmark first.','error');return} const idx=c.ids.indexOf(selected); if(idx<0){appToast('Selected landmark is not in this contour.','error');return} const next=idx+delta; if(next<0||next>=c.ids.length)return; [c.ids[idx],c.ids[next]]=[c.ids[next],c.ids[idx]]; renderGroups();draw();exportJson();}
function orderIds(ids){return isRotoProfile()?[...new Set(ids)]:[...new Set(ids)].sort((a,b)=>a-b)}
function assign(id,cid=activeChild){if(isGridProfile())return false; if(!cid||id<0||id>=MAX_LANDMARKS)return false; const found=findChild(cid); if(!found||found.child.ids.includes(id))return false; if(!assigned.has(id))assigned.set(id,new Set()); assigned.get(id).add(cid); found.child.ids.push(id); found.child.ids=orderIds(found.child.ids); refresh();return true;}
function unassign(id,cid=activeChild){if(cid&&pointHasChild(id,cid)){removePointFromChild(id,cid);} else {for(const childId of [...childIdsForPoint(id)])removePointFromChild(id,childId);} refresh();}
function addIdsToChild(c,ids){for(const n of ids){const id=Number(n); if(Number.isInteger(id)&&id>=0&&id<MAX_LANDMARKS&&!c.ids.includes(id)){if(!assigned.has(id))assigned.set(id,new Set()); assigned.get(id).add(c.id); c.ids.push(id);}} c.ids=orderIds(c.ids); if(!activeChild)activeChild=c.id;}
function parseIds(txt){const out=[]; for(const part of txt.split(/[ ,;\n]+/).filter(Boolean)){if(/^\d+-\d+$/.test(part)){let [a,b]=part.split('-').map(Number); if(a>b)[a,b]=[b,a]; for(let i=a;i<=b;i++)out.push(i)} else if(/^\d+$/.test(part))out.push(Number(part));} return [...new Set(out)].filter(i=>i>=0&&i<MAX_LANDMARKS);}
function buildNested(parentList=parents,profileName=currentProfile){const root={}; for(const p of parentList){root[p.name]={}; for(const c of p.children){if(isRotoProfile(profileName)){root[p.name][c.name]={ids:[...c.ids],openSpline:!!c.openSpline,color:c.color};} else {root[p.name][c.name]=[...c.ids].sort((a,b)=>a-b);}}} return root;}
function buildProfileExport(){saveProfileState(); if(isGridProfile())ensureGridProfileRoot(); const root={profiles:{}}; for(const name of PROFILE_NAMES)root.profiles[name]=isGridProfile(name)?buildGridExport():buildNested(profiles[name].parents,name); return root;}
function isProfileExport(data){return data&&typeof data==='object'&&!Array.isArray(data)&&data.profiles&&typeof data.profiles==='object'&&!Array.isArray(data.profiles);}
function exportJson(){const data=buildProfileExport(); el('jsonBox').value=JSON.stringify(data,null,2); validateMappingObject(data); return data;}
function gridIdsForImport(node){if(!node||typeof node!=='object')return []; if(Array.isArray(node.points))return node.points.map(p=>Number(p.id)).filter(Number.isInteger); if(Array.isArray(node.ids))return node.ids.flat?node.ids.flat(Infinity).map(Number).filter(Number.isInteger):[]; return [];}
function flattenForImport(obj){const items=[]; function addLeaf(path,ids,meta={}){if(path.length===0)items.push(['grid','grid',ids,meta]); else if(path.length===1)items.push([path[0],'all',ids,meta]); else items.push([path.slice(0,-1).join('.'),path[path.length-1],ids,meta]);} function walk(node,path){if(Array.isArray(node)){addLeaf(path,node); return;} if(node&&typeof node==='object'&&Number.isInteger(Number(node.cols))&&Number.isInteger(Number(node.rows))){addLeaf(path,gridIdsForImport(node),{}); return;} if(node&&typeof node==='object'&&Array.isArray(node.ids)){addLeaf(path,node.ids,{openSpline:!!node.openSpline,color:node.color}); return;} if(node&&typeof node==='object'){for(const [k,v] of Object.entries(node))walk(v,path.concat(k));}}
  walk(obj,[]); return items;}
function validateProfileMapping(data,label){const seen=new Map(), shared=[], invalid=[]; let total=0; for(const [pname,cname,ids] of flattenForImport(data)){const path=`${pname}.${cname}`; if(!Array.isArray(ids)){invalid.push(`${path}: not an array`); continue;} for(const raw of ids){const id=Number(raw); if(!Number.isInteger(id)||id<0||id>=MAX_LANDMARKS){invalid.push(`${path}: ${raw}`); continue;} total++; if(seen.has(id)){shared.push(`${id}: ${seen.get(id)} + ${path}`);} else seen.set(id,path);}}
  const lines=[`Profile: ${label}`,`Unique IDs: ${seen.size}`,`Total entries: ${total}`,`Free IDs: ${MAX_LANDMARKS-seen.size}`];
  if(shared.length)lines.push('',`Shared IDs (${shared.length}):`,...shared.slice(0,40),shared.length>40?'...':''); else lines.push('Shared IDs: none');
  if(invalid.length)lines.push('',`Out of range / invalid (${invalid.length}):`,...invalid.slice(0,40),invalid.length>40?'...':''); else lines.push('Out of range / invalid: none');
  return {lines,sharedCount:shared.length,invalidCount:invalid.length};
}
function validateMappingObject(data){const mappings=isProfileExport(data)?data.profiles:{[currentProfile]:data}; const lines=[`Range: 0-${MAX_LANDMARKS-1}`]; let sharedCount=0, invalidCount=0; for(const name of Object.keys(mappings)){const report=validateProfileMapping(mappings[name]||{},name); sharedCount+=report.sharedCount; invalidCount+=report.invalidCount; lines.push('',...report.lines);}
  el('validationBox').textContent=lines.filter(Boolean).join('\n');
  return {sharedCount, invalidCount};
}
function validateJsonBox(){let data; try{data=JSON.parse(el('jsonBox').value)}catch(e){el('validationBox').textContent='Invalid JSON: '+e.message; return null;} return validateMappingObject(data);}
function replaceProfileFromMapping(name,mapping){const previous={currentProfile,parents,assigned,activeChild}; profiles[name]=emptyProfile(); currentProfile=name; parents=profiles[name].parents; assigned=profiles[name].assigned; activeChild=null; if(isGridProfile(name)){importGridMapping(mapping||{});} else {let i=0; for(const [pname,cname,ids,meta] of flattenForImport(mapping||{})){const initialColor=(isRotoProfile(name)&&meta.color)?meta.color:COLORS[i++%COLORS.length]; const c=getOrCreateChild(pname,cname,initialColor); if(isRotoProfile(name))c.openSpline=!!meta.openSpline; addIdsToChild(c,ids);}} saveProfileState(); currentProfile=previous.currentProfile; if(previous.currentProfile===name){parents=profiles[name].parents; assigned=profiles[name].assigned; activeChild=profiles[name].activeChild;} else {parents=previous.parents; assigned=previous.assigned; activeChild=previous.activeChild;}}
async function importJson(){let data; try{data=JSON.parse(el('jsonBox').value)}catch(e){appToast('Invalid JSON.','error');return} const report=validateMappingObject(data); if(report.invalidCount&&!(await appConfirm('JSON contains invalid IDs. Import will skip out-of-range points. Continue?','Import JSON','Import',true)))return; const keepProfile=currentProfile; if(isProfileExport(data)){for(const name of PROFILE_NAMES)replaceProfileFromMapping(name,data.profiles[name]||{}); currentProfile=PROFILE_NAMES.includes(keepProfile)?keepProfile:'full';} else {replaceProfileFromMapping(currentProfile,data);} parents=profiles[currentProfile].parents; assigned=profiles[currentProfile].assigned; activeChild=profiles[currentProfile].activeChild; ensureGridProfileRoot(); el('profileSelect').value=currentProfile; updateProfileHint(); updateProfileUi(); refresh(); appToast('JSON imported.','ok');}
function loadInitialProfiles(){for(const name of PROFILE_NAMES)replaceProfileFromMapping(name,INITIAL_PROFILE_EXPORT.profiles[name]||{}); currentProfile='roto'; parents=profiles.roto.parents; assigned=profiles.roto.assigned; activeChild=profiles.roto.activeChild; resetSelection(); const ps=el('profileSelect'); if(ps)ps.value=currentProfile; updateProfileHint(); updateProfileUi(); refresh();}